# Generated by Django 4.0.3 on 2022-11-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='caption',
            new_name='name',
        ),
    ]
