# Generated by Django 4.0.3 on 2022-11-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_caption_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='caption',
        ),
    ]
