# Generated by Django 4.0.3 on 2022-11-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_delete_students_remove_image_caption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=False, upload_to='img/%y'),
        ),
    ]
