# Generated by Django 4.0.3 on 2022-11-16 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_remove_profile_caption_remove_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='avatar',
            field=models.ImageField(default='avatar.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='img/%y'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
