# Generated by Django 4.0.3 on 2022-11-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_image_avatar_alter_image_caption_alter_image_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='only_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_here', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
